#!/usr/bin/env python

import argparse
import getpass
from noderange import expand
import nodeconnection
import os
import paramiko
from paramiko import SSHException
import sys


def main():
    parser = argparse.ArgumentParser(
        description="Run a command on a set of nodes")
    parser.add_argument('-t', action="store_true", default=False)
    parser.add_argument('-v', action="store_true", default=False)
    parser.add_argument('-w', action="store", dest="where")
    parser.add_argument('-u', action="store", dest="user")
    parser.add_argument('-p', action="store", dest="password")
    parser.add_argument('command', nargs='*', action="store")
    args = parser.parse_args(sys.argv[1:])

    nodeconnection.runonnodes(args.where, " ".join(args.command),
                              dshbak=args.t, verbose=args.v,
                              user=args.user, password=args.password)

if __name__ == "__main__":
    main()
